---
common:
  disable_legacy_facts: true
  owner: 'ractf'
  honeycomb: false

.travis.yml:
  delete: true
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true

.github/workflows/spec.yml:
  unmanaged: false
.github/workflows/pr_test.yml:
  unmanaged: false
.github/workflows/nightly.yml:
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
